.TH GAD 8 "December 05, 2008"

.SH NAME
\fBgad\fP \- make directories group-accessible

.SH SYNOPSIS
\fBgad\fP [options] configuration-file

.SH DESCRIPTION
.B gad
ensures that the directories specified in the \fIconfiguration-file\fP are
accessible and stay accessible by certain ACL groups and / or users.
The script supports multiple reader, writer and/or executable groups per
directory. Simple exclude filters are supported as well.

The script is intended for work-group directories with multiple people
reading and writing to the directory. Default ACLs are used to prevent
participants (e.g. with a strict umask) from unintentionally creating files or
directories that are not accessible by everyone in the group. To catch corner
cases where that does not suffice, the script is usually called regularly from
a cron job.

.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-debug\fR
activate debugging output.
.TP
\fB\-s\fR, \fB\-\-simulate\fR
only simulate actions, do not actually perform them.

.SH SEE ALSO
.TP
\fIgad.conf\fP(8)

.SH AUTHOR
\fBgad\fP and this manual page were written by Fabian Knittel and put under the
GNU GPL; either version 2, or (at your option) any later version.
